export const JournalEventSchema = {
  type: "object",
  required: ["event_id", "timestamp", "session_id", "type", "payload"],
  properties: {
    event_id: { type: "string", minLength: 1 },
    timestamp: { type: "string", format: "date-time" },
    session_id: { type: "string", minLength: 1 },
    type: {
      type: "string",
      enum: [
        "session.created", "session.started", "session.completed", "session.failed",
        "session.aborted", "session.paused", "session.resumed",
        "planner.requested", "planner.plan_received", "planner.plan_rejected",
        "plan.accepted", "plan.replaced", "plan.criticized",
        "step.started", "step.succeeded", "step.failed",
        "permission.requested", "permission.granted", "permission.denied", "permission.observed_execution",
        "tool.requested", "tool.started", "tool.succeeded", "tool.failed",
        "policy.violated", "session.checkpoint", "limit.exceeded",
        "plugin.discovered", "plugin.loading", "plugin.loaded", "plugin.failed",
        "plugin.unloaded", "plugin.reloaded",
        "plugin.hook_fired", "plugin.hook_failed", "plugin.hook_circuit_open",
        "plugin.service_started", "plugin.service_stopped", "plugin.service_failed",
        "memory.lesson_extracted",
        "futility.detected",
        "usage.recorded",
        "context.budget_assessed",
        "context.delegation_started",
        "context.delegation_completed",
        "context.checkpoint_triggered",
        "context.summarize_triggered",
        "context.checkpoint_saved",
        "context.session_rotated",
        "scheduler.started",
        "scheduler.stopped",
        "scheduler.job_triggered",
        "scheduler.job_completed",
        "scheduler.job_failed",
        "scheduler.job_skipped",
        "scheduler.schedule_created",
        "scheduler.schedule_updated",
        "scheduler.schedule_deleted",
        "scheduler.schedule_paused",
        "swarm.started",
        "swarm.stopped",
        "swarm.peer_joined",
        "swarm.peer_left",
        "swarm.peer_suspected",
        "swarm.peer_unreachable",
        "swarm.task_delegated",
        "swarm.task_accepted",
        "swarm.task_result_received",
        "swarm.task_delegation_failed",
        "swarm.task_delegation_timeout",
        "swarm.gossip_round",
        "swarm.contract_created",
        "swarm.contract_completed",
        "swarm.contract_violated",
        "swarm.task_redelegated",
        "swarm.reputation_updated",
        "swarm.task_checkpoint_received",
        "swarm.task_checkpoint_missed",
        "swarm.task_monitoring_started",
        "swarm.task_monitoring_stopped",
        "swarm.task_cancelled",
        "swarm.budget_alert",
        "swarm.task_preempted",
        "swarm.attestation_chain_invalid",
        "swarm.task_verified",
        "swarm.task_verification_failed",
        "swarm.dispute_opened",
        "swarm.dispute_resolved",
        "swarm.task_decomposed",
        "swarm.reoptimization_triggered",
        "swarm.peer_redelegate_on_drift",
        "swarm.anomaly_detected",
        "swarm.data_access_violation",
        "swarm.monitoring_event_pushed",
        "swarm.pareto_selection_completed",
        "swarm.gaming_detected",
        "swarm.monitoring_level_negotiated",
        "swarm.reversibility_escalation",
        "swarm.root_cause_diagnosed",
        "swarm.peer_credential_verified",
        "swarm.peer_credential_rejected",
        "swarm.credential_issued",
        "swarm.task_decomposed_recursive",
        "swarm.proposals_generated",
        "swarm.dct_created",
        "swarm.dct_attenuated",
        "swarm.dct_validated",
        "swarm.dct_validation_failed",
        "swarm.dct_revoked",
        "swarm.sybil_detected",
        "swarm.collusion_detected",
        "swarm.proof_of_work_required",
        "swarm.proof_of_work_verified",
        "swarm.auction_created",
        "swarm.bid_received",
        "swarm.auction_awarded",
        "swarm.bond_held",
        "swarm.bond_released",
        "swarm.bond_slashed",
        "swarm.consensus_round_created",
        "swarm.consensus_vote_received",
        "swarm.consensus_reached",
        "swarm.consensus_failed",
        "swarm.firebreak_triggered",
        "swarm.firebreak_authority_requested",
        "swarm.delegatee_routed",
        "swarm.human_delegation_requested",
        "swarm.behavioral_observation_recorded",
        "swarm.behavioral_score_updated",
        "swarm.contract_renegotiation_requested",
        "swarm.contract_renegotiation_accepted",
        "swarm.contract_renegotiation_rejected",
        "swarm.friction_assessed",
        "swarm.friction_escalation_triggered",
        "swarm.friction_approval_received",
        "swarm.sabotage_detected",
        "swarm.feedback_discounted",
        "swarm.checkpoint_saved",
        "swarm.task_resumed_from_checkpoint",
        "swarm.bid_committed",
        "swarm.bid_revealed",
        "swarm.front_running_detected",
        "agent.started",
        "agent.progress",
        "agent.tool_call",
        "agent.completed",
        "agent.failed",
        "agent.aborted",
        "hook.input_modified",
        "vault.ingestion_started",
        "vault.ingestion_completed",
        "vault.object_created",
        "vault.object_updated",
        "vault.object_classified",
        "vault.entity_extracted",
        "vault.entity_deduplicated",
        "vault.link_created",
        "vault.context_generated",
        "vault.janitor_completed",
        "vault.vectorize_completed",
        "vault.relationships_discovered",
        "vault.dashboard_generated",
        "vault.insights_generated",
        "vault.dropzone_processed",
        "vault.error",
        "journal.disk_warning",
        "journal.disk_critical",
      ],
    },
    payload: { type: "object" },
    hash_prev: { type: "string" },
    seq: { type: "integer", minimum: 0 },
  },
  additionalProperties: false,
} as const;
