export const JournalEventSchema = {
  type: "object",
  required: ["event_id", "timestamp", "session_id", "type", "payload"],
  properties: {
    event_id: { type: "string", minLength: 1 },
    timestamp: { type: "string", format: "date-time" },
    session_id: { type: "string", minLength: 1 },
    type: {
      type: "string",
      enum: [
        "session.created", "session.started", "session.completed", "session.failed",
        "session.aborted", "session.paused", "session.resumed",
        "planner.requested", "planner.plan_received", "planner.plan_rejected",
        "plan.accepted", "plan.replaced", "plan.criticized",
        "step.started", "step.succeeded", "step.failed",
        "permission.requested", "permission.granted", "permission.denied", "permission.observed_execution",
        "tool.requested", "tool.started", "tool.succeeded", "tool.failed",
        "policy.violated", "session.checkpoint", "limit.exceeded",
        "plugin.discovered", "plugin.loading", "plugin.loaded", "plugin.failed",
        "plugin.unloaded", "plugin.reloaded",
        "plugin.hook_fired", "plugin.hook_failed", "plugin.hook_circuit_open",
        "plugin.service_started", "plugin.service_stopped", "plugin.service_failed",
        "memory.lesson_extracted",
        "futility.detected",
        "usage.recorded",
        "context.budget_assessed",
        "context.delegation_started",
        "context.delegation_completed",
        "context.checkpoint_triggered",
        "context.summarize_triggered",
        "context.checkpoint_saved",
        "context.session_rotated",
        "scheduler.started",
        "scheduler.stopped",
        "scheduler.job_triggered",
        "scheduler.job_completed",
        "scheduler.job_failed",
        "scheduler.job_skipped",
        "scheduler.schedule_created",
        "scheduler.schedule_updated",
        "scheduler.schedule_deleted",
        "scheduler.schedule_paused",
      ],
    },
    payload: { type: "object" },
    hash_prev: { type: "string" },
    seq: { type: "integer", minimum: 0 },
  },
  additionalProperties: false,
} as const;
